name: StandbyWatch
options:
  minimumXcodeGenVersion: 2.36.0
settings:
  base:
    DEVELOPMENT_TEAM: ""
    ORGANIZATIONNAME: "Standby"
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    WATCHOS_DEPLOYMENT_TARGET: 8.0

configs:
  Debug: debug
  Release: release

targets:

  StandbyWatchApp:
    type: application
    platform: watchOS
    deploymentTarget: "8.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.standby.watchapp.watchapp
    sources:
      - path: WatchApp
        optional: true
    info:
      path: WatchApp/Info.plist
      properties:
        CFBundleName: StandbyWatch
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        WKWatchKitApp: true
        WKCompanionAppBundleIdentifier: com.standby.watchapp.ios
    dependencies:
      - target: StandbyWatchExtension

  StandbyWatchExtension:
    type: app-extension
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: WatchExtension/Sources
      - path: WatchExtension/Resources
        type: folder
        optional: true
    info:
      path: WatchExtension/Resources/Info.plist
      properties:
        CFBundleName: StandbyWatchExtension
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        NSExtension:
          NSExtensionPointIdentifier: com.apple.watchkit
        NSHealthShareUsageDescription: "Heart rate is used to send vitals every 10 minutes."
        NSHealthUpdateUsageDescription: "App updates Health data as part of workouts."
        NSMicrophoneUsageDescription: "Microphone is used to record audio on Apple Watch."
    entitlements:
      path: WatchExtension/Entitlements/StandbyWatchExtension.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.standby.watchapp.watchapp.extension
        ENABLE_BITCODE: NO

schemes:
  StandbyWatch:
    build:
      targets:
        StandbyApp: [run]
        StandbyWatchApp: [run]
        StandbyWatchExtension: [run]
    run:
      config: Debug
